#!/usr/bin/env python
import os
import time
import sys

from tqdm import tqdm

from utils import SkimTreeBuilder


def parse_command_line(argv):
    """Parse the command line for the configuration file."""
    if argv is None:
        argv = sys.argv
    if len(argv) < 2:
        raise RuntimeError('No configuration file provided')
    else:
        config_file = os.path.basename(sys.argv[1])
        module_name, _ = os.path.splitext(config_file)
        try:
            config = __import__(module_name, globals(), locals(), [])
        except ImportError:
            raise
        return config


def main(argv=None):
    sys.dont_write_bytecode = True
    config = parse_command_line(argv)
    skim_tree_builder = SkimTreeBuilder(config.input_pattern, config.destination)
    for name, args in tqdm(config.samples.items()):
        scale_factor, input_tokens = args
        start = time.time()
        skim_tree_builder.run(name, input_tokens, config.keep_branches, config.new_branches, scale_factor)
        end = time.time()
        tqdm.write('Finished building skimmed tree for {0} in {1:.2f}s'.format(name, end - start))


if __name__ == '__main__':

    status = main()
    sys.exit(status)

